/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetAlliancesAllianceIdOk {
    /**
     * the full name of the alliance
     */
    name: string;
    /**
     * ID of the character that created the alliance
     */
    creatorId: number;
    /**
     * ID of the corporation that created the alliance
     */
    creatorCorporationId: number;
    /**
     * the short name of the alliance
     */
    ticker: string;
    /**
     * the executor corporation ID, if this alliance is not closed
     */
    executorCorporationId?: number;
    /**
     * date_founded string
     */
    dateFounded: Date;
    /**
     * Faction ID this alliance is fighting for, if this alliance is enlisted in factional warfare
     */
    factionId?: number;
}
