/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * mining object
 */
export interface GetCharactersCharacterIdStatsMining {
    /**
     * drone_mine integer
     */
    droneMine?: number;
    /**
     * ore_arkonor integer
     */
    oreArkonor?: number;
    /**
     * ore_bistot integer
     */
    oreBistot?: number;
    /**
     * ore_crokite integer
     */
    oreCrokite?: number;
    /**
     * ore_dark_ochre integer
     */
    oreDarkOchre?: number;
    /**
     * ore_gneiss integer
     */
    oreGneiss?: number;
    /**
     * ore_harvestable_cloud integer
     */
    oreHarvestableCloud?: number;
    /**
     * ore_hedbergite integer
     */
    oreHedbergite?: number;
    /**
     * ore_hemorphite integer
     */
    oreHemorphite?: number;
    /**
     * ore_ice integer
     */
    oreIce?: number;
    /**
     * ore_jaspet integer
     */
    oreJaspet?: number;
    /**
     * ore_kernite integer
     */
    oreKernite?: number;
    /**
     * ore_mercoxit integer
     */
    oreMercoxit?: number;
    /**
     * ore_omber integer
     */
    oreOmber?: number;
    /**
     * ore_plagioclase integer
     */
    orePlagioclase?: number;
    /**
     * ore_pyroxeres integer
     */
    orePyroxeres?: number;
    /**
     * ore_scordite integer
     */
    oreScordite?: number;
    /**
     * ore_spodumain integer
     */
    oreSpodumain?: number;
    /**
     * ore_veldspar integer
     */
    oreVeldspar?: number;
}
