/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * inventory object
 */
export interface GetCharactersCharacterIdStatsInventory {
    /**
     * abandon_loot_quantity integer
     */
    abandonLootQuantity?: number;
    /**
     * trash_item_quantity integer
     */
    trashItemQuantity?: number;
}
