/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdFwStatsKills } from './getCharactersCharacterIdFwStatsKills';
import { GetCharactersCharacterIdFwStatsVictoryPoints } from './getCharactersCharacterIdFwStatsVictoryPoints';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFwStatsOk {
    /**
     * The faction the given character is enlisted to fight for. Will not be included if character is not enlisted in faction warfare
     */
    factionId?: number;
    /**
     * The enlistment date of the given character into faction warfare. Will not be included if character is not enlisted in faction warfare
     */
    enlistedOn?: Date;
    /**
     * The given character's current faction rank
     */
    currentRank?: number;
    /**
     * The given character's highest faction rank achieved
     */
    highestRank?: number;
    kills: GetCharactersCharacterIdFwStatsKills;
    victoryPoints: GetCharactersCharacterIdFwStatsVictoryPoints;
}
