/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Extra information for different type of transaction
 */
export interface GetCharactersCharacterIdWalletJournalExtraInfo {
    /**
     * location_id integer
     */
    locationId?: number;
    /**
     * transaction_id integer
     */
    transactionId?: number;
    /**
     * npc_name string
     */
    npcName?: string;
    /**
     * npc_id integer
     */
    npcId?: number;
    /**
     * destroyed_ship_type_id integer
     */
    destroyedShipTypeId?: number;
    /**
     * character_id integer
     */
    characterId?: number;
    /**
     * corporation_id integer
     */
    corporationId?: number;
    /**
     * alliance_id integer
     */
    allianceId?: number;
    /**
     * job_id integer
     */
    jobId?: number;
    /**
     * contract_id integer
     */
    contractId?: number;
    /**
     * system_id integer
     */
    systemId?: number;
    /**
     * planet_id integer
     */
    planetId?: number;
}
