/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Summary of kills done by the given character against enemy factions
 */
export interface GetCharactersCharacterIdFwStatsKills {
    /**
     * Yesterday's total number of kills by a given character against enemy factions
     */
    yesterday: number;
    /**
     * Last week's total number of kills by a given character against enemy factions
     */
    lastWeek: number;
    /**
     * Total number of kills by a given character against enemy factions since the character enlisted
     */
    total: number;
}
