/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * link object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdLink {
    /**
     * source_pin_id integer
     */
    sourcePinId: number;
    /**
     * destination_pin_id integer
     */
    destinationPinId: number;
    /**
     * link_level integer
     */
    linkLevel: number;
}
