/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * pve object
 */
export interface GetCharactersCharacterIdStatsPve {
    /**
     * dungeons_completed_agent integer
     */
    dungeonsCompletedAgent?: number;
    /**
     * dungeons_completed_distribution integer
     */
    dungeonsCompletedDistribution?: number;
    /**
     * missions_succeeded integer
     */
    missionsSucceeded?: number;
    /**
     * missions_succeeded_epic_arc integer
     */
    missionsSucceededEpicArc?: number;
}
