/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdMembertracking200Ok {
    /**
     * character_id integer
     */
    characterId: number;
    /**
     * start_date string
     */
    startDate?: Date;
    /**
     * base_id integer
     */
    baseId?: number;
    /**
     * logon_date string
     */
    logonDate?: Date;
    /**
     * logoff_date string
     */
    logoffDate?: Date;
    /**
     * location_id integer
     */
    locationId?: number;
    /**
     * ship_type_id integer
     */
    shipTypeId?: number;
}
