/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdContacts200Ok {
    /**
     * Standing of the contact
     */
    standing: number;
    /**
     * contact_type string
     */
    contactType: GetCharactersCharacterIdContacts200Ok.ContactTypeEnum;
    /**
     * contact_id integer
     */
    contactId: number;
    /**
     * Whether this contact is being watched
     */
    isWatched?: boolean;
    /**
     * Whether this contact is in the blocked list. Note a missing value denotes unknown, not true or false
     */
    isBlocked?: boolean;
    /**
     * Custom label of the contact
     */
    labelId?: number;
}
export namespace GetCharactersCharacterIdContacts200Ok {
    export type ContactTypeEnum = 'character' | 'corporation' | 'alliance' | 'faction';
    export const ContactTypeEnum = {
        Character: 'character' as ContactTypeEnum,
        Corporation: 'corporation' as ContactTypeEnum,
        Alliance: 'alliance' as ContactTypeEnum,
        Faction: 'faction' as ContactTypeEnum
    }
}
