/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * service object
 */
export interface GetCorporationsCorporationIdOutpostsOutpostIdService {
    /**
     * service_name string
     */
    serviceName: GetCorporationsCorporationIdOutpostsOutpostIdService.ServiceNameEnum;
    /**
     * minimum_standing number
     */
    minimumStanding: number;
    /**
     * surcharge_per_bad_standing number
     */
    surchargePerBadStanding: number;
    /**
     * discount_per_good_standing number
     */
    discountPerGoodStanding: number;
}
export namespace GetCorporationsCorporationIdOutpostsOutpostIdService {
    export type ServiceNameEnum = 'Bounty Missions' | 'Assassination Missions' | 'Courier Missions' | 'Interbus' | 'Reprocessing Plant' | 'Refinery' | 'Market' | 'Black Market' | 'Stock Exchange' | 'Cloning' | 'Surgery' | 'DNA Therapy' | 'Repair Facilities' | 'Factory' | 'Laboratory' | 'Gambling' | 'Fitting' | 'Paintshop' | 'News' | 'Storage' | 'Insurance' | 'Docking' | 'Office Rental' | 'Jump Clone Facility' | 'Loyalty Point Store' | 'Navy Offices' | 'Security Office';
    export const ServiceNameEnum = {
        BountyMissions: 'Bounty Missions' as ServiceNameEnum,
        AssassinationMissions: 'Assassination Missions' as ServiceNameEnum,
        CourierMissions: 'Courier Missions' as ServiceNameEnum,
        Interbus: 'Interbus' as ServiceNameEnum,
        ReprocessingPlant: 'Reprocessing Plant' as ServiceNameEnum,
        Refinery: 'Refinery' as ServiceNameEnum,
        Market: 'Market' as ServiceNameEnum,
        BlackMarket: 'Black Market' as ServiceNameEnum,
        StockExchange: 'Stock Exchange' as ServiceNameEnum,
        Cloning: 'Cloning' as ServiceNameEnum,
        Surgery: 'Surgery' as ServiceNameEnum,
        DNATherapy: 'DNA Therapy' as ServiceNameEnum,
        RepairFacilities: 'Repair Facilities' as ServiceNameEnum,
        Factory: 'Factory' as ServiceNameEnum,
        Laboratory: 'Laboratory' as ServiceNameEnum,
        Gambling: 'Gambling' as ServiceNameEnum,
        Fitting: 'Fitting' as ServiceNameEnum,
        Paintshop: 'Paintshop' as ServiceNameEnum,
        News: 'News' as ServiceNameEnum,
        Storage: 'Storage' as ServiceNameEnum,
        Insurance: 'Insurance' as ServiceNameEnum,
        Docking: 'Docking' as ServiceNameEnum,
        OfficeRental: 'Office Rental' as ServiceNameEnum,
        JumpCloneFacility: 'Jump Clone Facility' as ServiceNameEnum,
        LoyaltyPointStore: 'Loyalty Point Store' as ServiceNameEnum,
        NavyOffices: 'Navy Offices' as ServiceNameEnum,
        SecurityOffice: 'Security Office' as ServiceNameEnum
    }
}
