/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * graphic object
 */
export interface GetCharactersCharacterIdMedalsGraphic {
    /**
     * part integer
     */
    part: number;
    /**
     * layer integer
     */
    layer: number;
    /**
     * graphic string
     */
    graphic: string;
    /**
     * color integer
     */
    color?: number;
}
