/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdStatsCharacter } from './getCharactersCharacterIdStatsCharacter';
import { GetCharactersCharacterIdStatsCombat } from './getCharactersCharacterIdStatsCombat';
import { GetCharactersCharacterIdStatsIndustry } from './getCharactersCharacterIdStatsIndustry';
import { GetCharactersCharacterIdStatsInventory } from './getCharactersCharacterIdStatsInventory';
import { GetCharactersCharacterIdStatsIsk } from './getCharactersCharacterIdStatsIsk';
import { GetCharactersCharacterIdStatsMarket } from './getCharactersCharacterIdStatsMarket';
import { GetCharactersCharacterIdStatsMining } from './getCharactersCharacterIdStatsMining';
import { GetCharactersCharacterIdStatsModule } from './getCharactersCharacterIdStatsModule';
import { GetCharactersCharacterIdStatsOrbital } from './getCharactersCharacterIdStatsOrbital';
import { GetCharactersCharacterIdStatsPve } from './getCharactersCharacterIdStatsPve';
import { GetCharactersCharacterIdStatsSocial } from './getCharactersCharacterIdStatsSocial';
import { GetCharactersCharacterIdStatsTravel } from './getCharactersCharacterIdStatsTravel';


/**
 * Aggregate stats for a year
 */
export interface GetCharactersCharacterIdStats200Ok {
    /**
     * Gregorian year for this set of aggregates
     */
    year: number;
    character?: GetCharactersCharacterIdStatsCharacter;
    combat?: GetCharactersCharacterIdStatsCombat;
    industry?: GetCharactersCharacterIdStatsIndustry;
    inventory?: GetCharactersCharacterIdStatsInventory;
    isk?: GetCharactersCharacterIdStatsIsk;
    market?: GetCharactersCharacterIdStatsMarket;
    mining?: GetCharactersCharacterIdStatsMining;
    module?: GetCharactersCharacterIdStatsModule;
    orbital?: GetCharactersCharacterIdStatsOrbital;
    pve?: GetCharactersCharacterIdStatsPve;
    social?: GetCharactersCharacterIdStatsSocial;
    travel?: GetCharactersCharacterIdStatsTravel;
}
