/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Optional object that is returned if a bookmark was made on a planet or a random location in space.
 */
export interface GetCorporationsCorporationIdBookmarksCoordinates {
    /**
     * x number
     */
    x: number;
    /**
     * y number
     */
    y: number;
    /**
     * z number
     */
    z: number;
}
