/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * module object
 */
export interface GetCharactersCharacterIdStatsModule {
    /**
     * activations_armor_hardener integer
     */
    activationsArmorHardener?: number;
    /**
     * activations_armor_repair_unit integer
     */
    activationsArmorRepairUnit?: number;
    /**
     * activations_armor_resistance_shift_hardener integer
     */
    activationsArmorResistanceShiftHardener?: number;
    /**
     * activations_automated_targeting_system integer
     */
    activationsAutomatedTargetingSystem?: number;
    /**
     * activations_bastion integer
     */
    activationsBastion?: number;
    /**
     * activations_bomb_launcher integer
     */
    activationsBombLauncher?: number;
    /**
     * activations_capacitor_booster integer
     */
    activationsCapacitorBooster?: number;
    /**
     * activations_cargo_scanner integer
     */
    activationsCargoScanner?: number;
    /**
     * activations_cloaking_device integer
     */
    activationsCloakingDevice?: number;
    /**
     * activations_clone_vat_bay integer
     */
    activationsCloneVatBay?: number;
    /**
     * activations_cynosural_field integer
     */
    activationsCynosuralField?: number;
    /**
     * activations_damage_control integer
     */
    activationsDamageControl?: number;
    /**
     * activations_data_miners integer
     */
    activationsDataMiners?: number;
    /**
     * activations_drone_control_unit integer
     */
    activationsDroneControlUnit?: number;
    /**
     * activations_drone_tracking_modules integer
     */
    activationsDroneTrackingModules?: number;
    /**
     * activations_eccm integer
     */
    activationsEccm?: number;
    /**
     * activations_ecm integer
     */
    activationsEcm?: number;
    /**
     * activations_ecm_burst integer
     */
    activationsEcmBurst?: number;
    /**
     * activations_energy_destabilizer integer
     */
    activationsEnergyDestabilizer?: number;
    /**
     * activations_energy_vampire integer
     */
    activationsEnergyVampire?: number;
    /**
     * activations_energy_weapon integer
     */
    activationsEnergyWeapon?: number;
    /**
     * activations_festival_launcher integer
     */
    activationsFestivalLauncher?: number;
    /**
     * activations_frequency_mining_laser integer
     */
    activationsFrequencyMiningLaser?: number;
    /**
     * activations_fueled_armor_repairer integer
     */
    activationsFueledArmorRepairer?: number;
    /**
     * activations_fueled_shield_booster integer
     */
    activationsFueledShieldBooster?: number;
    /**
     * activations_gang_coordinator integer
     */
    activationsGangCoordinator?: number;
    /**
     * activations_gas_cloud_harvester integer
     */
    activationsGasCloudHarvester?: number;
    /**
     * activations_hull_repair_unit integer
     */
    activationsHullRepairUnit?: number;
    /**
     * activations_hybrid_weapon integer
     */
    activationsHybridWeapon?: number;
    /**
     * activations_industrial_core integer
     */
    activationsIndustrialCore?: number;
    /**
     * activations_interdiction_sphere_launcher integer
     */
    activationsInterdictionSphereLauncher?: number;
    /**
     * activations_micro_jump_drive integer
     */
    activationsMicroJumpDrive?: number;
    /**
     * activations_mining_laser integer
     */
    activationsMiningLaser?: number;
    /**
     * activations_missile_launcher integer
     */
    activationsMissileLauncher?: number;
    /**
     * activations_passive_targeting_system integer
     */
    activationsPassiveTargetingSystem?: number;
    /**
     * activations_probe_launcher integer
     */
    activationsProbeLauncher?: number;
    /**
     * activations_projected_eccm integer
     */
    activationsProjectedEccm?: number;
    /**
     * activations_projectile_weapon integer
     */
    activationsProjectileWeapon?: number;
    /**
     * activations_propulsion_module integer
     */
    activationsPropulsionModule?: number;
    /**
     * activations_remote_armor_repairer integer
     */
    activationsRemoteArmorRepairer?: number;
    /**
     * activations_remote_capacitor_transmitter integer
     */
    activationsRemoteCapacitorTransmitter?: number;
    /**
     * activations_remote_ecm_burst integer
     */
    activationsRemoteEcmBurst?: number;
    /**
     * activations_remote_hull_repairer integer
     */
    activationsRemoteHullRepairer?: number;
    /**
     * activations_remote_sensor_booster integer
     */
    activationsRemoteSensorBooster?: number;
    /**
     * activations_remote_sensor_damper integer
     */
    activationsRemoteSensorDamper?: number;
    /**
     * activations_remote_shield_booster integer
     */
    activationsRemoteShieldBooster?: number;
    /**
     * activations_remote_tracking_computer integer
     */
    activationsRemoteTrackingComputer?: number;
    /**
     * activations_salvager integer
     */
    activationsSalvager?: number;
    /**
     * activations_sensor_booster integer
     */
    activationsSensorBooster?: number;
    /**
     * activations_shield_booster integer
     */
    activationsShieldBooster?: number;
    /**
     * activations_shield_hardener integer
     */
    activationsShieldHardener?: number;
    /**
     * activations_ship_scanner integer
     */
    activationsShipScanner?: number;
    /**
     * activations_siege integer
     */
    activationsSiege?: number;
    /**
     * activations_smart_bomb integer
     */
    activationsSmartBomb?: number;
    /**
     * activations_stasis_web integer
     */
    activationsStasisWeb?: number;
    /**
     * activations_strip_miner integer
     */
    activationsStripMiner?: number;
    /**
     * activations_super_weapon integer
     */
    activationsSuperWeapon?: number;
    /**
     * activations_survey_scanner integer
     */
    activationsSurveyScanner?: number;
    /**
     * activations_target_breaker integer
     */
    activationsTargetBreaker?: number;
    /**
     * activations_target_painter integer
     */
    activationsTargetPainter?: number;
    /**
     * activations_tracking_computer integer
     */
    activationsTrackingComputer?: number;
    /**
     * activations_tracking_disruptor integer
     */
    activationsTrackingDisruptor?: number;
    /**
     * activations_tractor_beam integer
     */
    activationsTractorBeam?: number;
    /**
     * activations_triage integer
     */
    activationsTriage?: number;
    /**
     * activations_warp_disrupt_field_generator integer
     */
    activationsWarpDisruptFieldGenerator?: number;
    /**
     * activations_warp_scrambler integer
     */
    activationsWarpScrambler?: number;
    /**
     * link_weapons integer
     */
    linkWeapons?: number;
    /**
     * overload integer
     */
    overload?: number;
    /**
     * repairs integer
     */
    repairs?: number;
}
