/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetFwStatsKills } from './getFwStatsKills';
import { GetFwStatsVictoryPoints } from './getFwStatsVictoryPoints';


/**
 * 200 ok object
 */
export interface GetFwStats200Ok {
    /**
     * faction_id integer
     */
    factionId: number;
    /**
     * How many pilots fight for the given faction
     */
    pilots: number;
    /**
     * The number of solar systems controlled by the given faction
     */
    systemsControlled: number;
    kills: GetFwStatsKills;
    victoryPoints: GetFwStatsVictoryPoints;
}
