/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetFleetsFleetIdWingsSquad } from './getFleetsFleetIdWingsSquad';


/**
 * 200 ok object
 */
export interface GetFleetsFleetIdWings200Ok {
    /**
     * name string
     */
    name: string;
    /**
     * id integer
     */
    id: number;
    /**
     * squads array
     */
    squads: Array<GetFleetsFleetIdWingsSquad>;
}
