/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * level object
 */
export interface GetInsurancePricesLevel {
    /**
     * cost number
     */
    cost: number;
    /**
     * payout number
     */
    payout: number;
    /**
     * Localized insurance level
     */
    name: string;
}
