/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * participant object
 */
export interface GetSovereigntyCampaignsParticipant {
    /**
     * alliance_id integer
     */
    allianceId: number;
    /**
     * score number
     */
    score: number;
}
