/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetUniverseStargatesStargateIdDestination } from './getUniverseStargatesStargateIdDestination';
import { GetUniverseStargatesStargateIdPosition } from './getUniverseStargatesStargateIdPosition';


/**
 * 200 ok object
 */
export interface GetUniverseStargatesStargateIdOk {
    /**
     * stargate_id integer
     */
    stargateId: number;
    /**
     * name string
     */
    name: string;
    /**
     * type_id integer
     */
    typeId: number;
    position: GetUniverseStargatesStargateIdPosition;
    /**
     * The solar system this stargate is in
     */
    systemId: number;
    destination: GetUniverseStargatesStargateIdDestination;
}
