/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface PostCharactersAffiliation200Ok {
    /**
     * The character's ID
     */
    characterId: number;
    /**
     * The character's corporation ID
     */
    corporationId: number;
    /**
     * The character's alliance ID, if their corporation is in an alliance
     */
    allianceId?: number;
    /**
     * The character's faction ID, if their corporation is in a faction
     */
    factionId?: number;
}
