export * from './alliance.service';
import { AllianceService } from './alliance.service';
export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './bookmarks.service';
import { BookmarksService } from './bookmarks.service';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './character.service';
import { CharacterService } from './character.service';
export * from './clones.service';
import { ClonesService } from './clones.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './contracts.service';
import { ContractsService } from './contracts.service';
export * from './corporation.service';
import { CorporationService } from './corporation.service';
export * from './dogma.service';
import { DogmaService } from './dogma.service';
export * from './factionWarfare.service';
import { FactionWarfareService } from './factionWarfare.service';
export * from './fittings.service';
import { FittingsService } from './fittings.service';
export * from './fleets.service';
import { FleetsService } from './fleets.service';
export * from './incursions.service';
import { IncursionsService } from './incursions.service';
export * from './industry.service';
import { IndustryService } from './industry.service';
export * from './insurance.service';
import { InsuranceService } from './insurance.service';
export * from './killmails.service';
import { KillmailsService } from './killmails.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './loyalty.service';
import { LoyaltyService } from './loyalty.service';
export * from './mail.service';
import { MailService } from './mail.service';
export * from './market.service';
import { MarketService } from './market.service';
export * from './opportunities.service';
import { OpportunitiesService } from './opportunities.service';
export * from './planetaryInteraction.service';
import { PlanetaryInteractionService } from './planetaryInteraction.service';
export * from './routes.service';
import { RoutesService } from './routes.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './skills.service';
import { SkillsService } from './skills.service';
export * from './sovereignty.service';
import { SovereigntyService } from './sovereignty.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './universe.service';
import { UniverseService } from './universe.service';
export * from './userInterface.service';
import { UserInterfaceService } from './userInterface.service';
export * from './wallet.service';
import { WalletService } from './wallet.service';
export * from './wars.service';
import { WarsService } from './wars.service';
export const APIS = [AllianceService, AssetsService, BookmarksService, CalendarService, CharacterService, ClonesService, ContactsService, ContractsService, CorporationService, DogmaService, FactionWarfareService, FittingsService, FleetsService, IncursionsService, IndustryService, InsuranceService, KillmailsService, LocationService, LoyaltyService, MailService, MarketService, OpportunitiesService, PlanetaryInteractionService, RoutesService, SearchService, SkillsService, SovereigntyService, StatusService, UniverseService, UserInterfaceService, WalletService, WarsService];
